title = "るいもの戯言"

# The URL the site will be built for
base_url = "https://ruimo.github.io/ruimo-blog"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "kita"

generate_feeds = true

taxonomies = [
    { name = "tags", feed = true },  # "tags" という名前のタクソノミーを有効にする
]

[markdown]
highlight_code = true
render_emoji = true

[extra]
# Put all your custom variables here

admonition = true

# Enable KaTex math formula support globally.
math = true
# Enable mermaid support globally.
mermaid = true
# Enable comment support globally.
comment = true

og_image = "images/logo.gif"

[[extra.menu]]
name = "タグ"
url = "$BASE_URL/tags"

[[extra.menu]]
name = "DIY"
url = "$BASE_URL/diy"

[[extra.menu]]
name = "Piano"
url = "$BASE_URL/piano"

[[extra.menu]]
name = "Tools"
url = "$BASE_URL/tools"

[[extra.menu]]
name = "Publication"
url = "https://static.ruimo.com/publication"

[extra.giscus]
repo = "ruimo/ruimo-blog"
repo_id = "R_kgDON3pwEQ"
category = "Announcements"
category_id = "DIC_kwDON3pwEc4Cm2vv"
mapping = "pathname"
strict = "0"
reactions_enabled = "1"
emit_metadata = "0"
input_position = "bottom"
theme = "preferred_color_scheme"
lang = "ja"
loading = "lazy"
